version: "3.8"

services:

  backend:
    build: ./backend
    container_name: smartaiops-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - smartaiops-db:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: smartaiops-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  smartaiops-db: